"""Generate docker-compose.yml from spec.yaml.

Emit-only: writes the file, does not run Docker.
"""

from pathlib import Path
from textwrap import dedent

import yaml


COMPOSE_HEADER = dedent("""\
    # =============================================================================
    # AUTO-GENERATED by constructor/build_compose.py — do not hand-edit.
    # Regenerate with: python3 -m constructor up <profile_dir> --emit-only
    # =============================================================================
""")


def build_compose(spec: dict, profile_relpath: str = "profiles/default") -> str:
    """Return docker-compose.yml content as a string."""

    runtime_env = spec.get("runtime_env") or {
        "AWS_ENDPOINT_URL": "http://localstack:4566",
        "DBM_BASE_URL": "http://microcks:8080/dbm",
        "CAL_BASE_URL": "http://microcks:8080/cal",
        "POSTGRES_DSN": "postgresql://postgres:postgres@postgres:5432/aap_sandbox",
        "AWS_DEFAULT_REGION": "us-east-1",
        "AWS_ACCESS_KEY_ID": "test",
        "AWS_SECRET_ACCESS_KEY": "test",
        "SANDBOX_SEED": "42",
    }

    # NOTE on naming:
    #   When run via `docker compose --project-directory <Sandbox/core>` the
    #   project name is "core", and the network gets prefixed: core_sandbox-net.
    #   LocalStack must be told the *post-prefix* network name so it can attach
    #   spawned Lambda containers correctly. Bare "sandbox-net" hangs every invoke.
    project_name = "core"
    lambda_docker_network = f"{project_name}_sandbox-net"

    compose = {
        # Compose v2 ignores `version:`. Omit it to suppress warnings.
        "services": {
            "localstack": {
                # Community image, free. Pro (`:4-ultimate`) requires a license
                # we don't have and is not needed for structural smoke tests.
                "image": "localstack/localstack:4",
                "ports": ["4566:4566"],
                "environment": {
                    "LOCALSTACK_PERSISTENCE": "0",
                    "SERVICES": "lambda,s3,dynamodb,stepfunctions,glue,iam,sts",
                    "LAMBDA_DOCKER_NETWORK": lambda_docker_network,
                    "DEBUG": "0",
                },
                # LocalStack needs the host docker socket to spawn Lambda
                # runtime containers. Without this, every invoke fails with
                # "Docker not available".
                "volumes": ["/var/run/docker.sock:/var/run/docker.sock"],
                "networks": ["sandbox-net"],
                "depends_on": ["microcks", "postgres"],
            },
            "microcks": {
                "image": "quay.io/microcks/microcks-uber:1.10.0",
                "ports": ["8080:8080"],
                "networks": ["sandbox-net"],
            },
            "postgres": {
                "image": "postgres:16",
                # Host 5433 → container 5432: avoids collision with a native
                # Postgres on the operator's laptop bound to host 5432.
                "ports": ["5433:5432"],
                "environment": {
                    "POSTGRES_DB": "aap_sandbox",
                    "POSTGRES_USER": "postgres",
                    "POSTGRES_PASSWORD": "postgres",
                },
                "volumes": [
                    f"./{profile_relpath}/attachments/postgres/ddl/generated:/docker-entrypoint-initdb.d:ro"
                ],
                "networks": ["sandbox-net"],
            },
            # Glue intentionally not run as a separate container. LocalStack
            # community provides the Glue API stub. If real mb4.yml execution
            # is ever needed (Phase 2+), add it back with explicit command.
            "runner": {
                "image": "python:3.11-slim",
                "environment": runtime_env,
                "volumes": [
                    "./:/workspace:rw"
                ],
                "working_dir": "/workspace",
                "networks": ["sandbox-net"],
                "depends_on": ["localstack", "microcks", "postgres"],
                "command": "tail -f /dev/null",
            },
        },
        "networks": {
            "sandbox-net": {"driver": "bridge"},
        },
    }

    body = yaml.safe_dump(compose, sort_keys=False, default_flow_style=False)
    return COMPOSE_HEADER + body
