"""Generate seeder.sh — the script that, after `docker compose up`, runs
all the inside-container setup commands (S3 buckets, Lambda registration,
Microcks imports, etc.).

Emit-only: writes the file. Operator inspects, then runs it manually.
"""

from pathlib import Path
from textwrap import dedent

SEEDER_HEADER = dedent("""\
    #!/usr/bin/env bash
    # =============================================================================
    # AUTO-GENERATED by constructor/build_seeder.py — do not hand-edit.
    # Regenerate with: python3 -m constructor up <profile_dir> --emit-only
    #
    # Run AFTER `docker compose up -d --wait`. Idempotent operations preferred;
    # any non-idempotent step is annotated.
    # =============================================================================

    set -euo pipefail

    AWS_LOCAL="aws --endpoint-url http://localhost:4566 --region us-east-1"
    export AWS_ACCESS_KEY_ID=test
    export AWS_SECRET_ACCESS_KEY=test

    echo "==> waiting for services to be healthy"
    until curl -fsS http://localhost:4566/_localstack/health > /dev/null; do sleep 1; done
    until curl -fsS http://localhost:8080/api/keycloak/config > /dev/null 2>&1 || \\
          curl -fsS http://localhost:8080/                  > /dev/null; do sleep 1; done

""")


def env_to_aws_cli(env: dict) -> str:
    """Convert {K: V} → 'Variables={K=V,K2=V2}' for aws lambda create-function."""
    if not env:
        return ""
    pairs = ",".join(f"{k}={v}" for k, v in env.items())
    return f"Variables={{{pairs}}}"


def build_seeder(spec: dict, profile_relpath: str = "profiles/default") -> str:
    """Return seeder.sh content."""
    out = [SEEDER_HEADER]
    attach = f"{profile_relpath}/attachments"

    # ─── S3 buckets ──────────────────────────────────────────────────────────
    out.append("echo '==> creating S3 buckets'")
    for b in spec.get("s3_buckets") or []:
        bucket = b["bucket_name"]
        out.append(f'$AWS_LOCAL s3 mb "s3://{bucket}" 2>/dev/null || true')
    out.append("")

    out.append("echo '==> seeding S3 with parquets'")
    out.append(
        f'$AWS_LOCAL s3 cp "{attach}/parquets/" '
        f'"s3://etl_workflow-devl-fcdl-pp80-staging/input/" --recursive 2>/dev/null || true'
    )
    out.append("")

    # ─── DynamoDB tables ─────────────────────────────────────────────────────
    out.append("echo '==> creating DynamoDB tables'")
    for ddb in spec.get("dynamodb") or []:
        attrs = ",".join(
            f'AttributeName={a["name"]},AttributeType={a["type"]}'
            for a in ddb["attribute_definitions"]
        )
        ks = f'AttributeName={ddb["hash_key"]},KeyType=HASH'
        if ddb.get("sort_key"):
            ks += f' AttributeName={ddb["sort_key"]},KeyType=RANGE'
        out.append(
            f'$AWS_LOCAL dynamodb create-table '
            f'--table-name {ddb["table_name"]} '
            f'--attribute-definitions {attrs} '
            f'--key-schema {ks} '
            f'--billing-mode PAY_PER_REQUEST 2>/dev/null || true'
        )
    out.append("")

    # ─── Lambdas ─────────────────────────────────────────────────────────────
    out.append("echo '==> registering Lambdas'")
    runtime_env = spec.get("runtime_env") or {
        "AWS_ENDPOINT_URL": "http://localstack:4566",
        "DBM_BASE_URL": "http://microcks:8080/dbm",
        "CAL_BASE_URL": "http://microcks:8080/cal",
        "POSTGRES_DSN": "postgresql://postgres:postgres@postgres:5432/aap_sandbox",
    }
    for lam in spec.get("lambdas") or []:
        env = {**runtime_env, **(lam.get("env_vars") or {})}
        env_str = env_to_aws_cli(env)
        zip_logical = lam["source_archive"]
        zip_path = f"{attach}/lambdas/generated/{zip_logical}"
        out.append(
            f'$AWS_LOCAL lambda create-function '
            f'--function-name {lam["lambda_name"]} '
            f'--runtime {lam["runtime"]} '
            f'--handler {lam["handler"]} '
            f'--role arn:aws:iam::000000000000:role/lambda-role '
            f'--timeout {lam.get("timeout_seconds", 30)} '
            f'--memory-size {lam.get("memory_mb", 256)} '
            f'--environment "{env_str}" '
            f'--zip-file fileb://{zip_path} 2>/dev/null || true'
        )
    out.append("")

    # ─── Glue jobs ───────────────────────────────────────────────────────────
    out.append("echo '==> registering Glue jobs'")
    for gj in spec.get("glue_jobs") or []:
        out.append(
            f'$AWS_LOCAL glue create-job '
            f'--name {gj["job_name"]} '
            f'--role arn:aws:iam::000000000000:role/glue-role '
            f'--command "Name=glueetl,ScriptLocation=s3://glue-scripts/{gj["job_name"]}.py" '
            f'--glue-version "{gj.get("glue_version", "5.0")}" 2>/dev/null || true'
        )
    out.append("")

    # ─── Step Functions ──────────────────────────────────────────────────────
    out.append("echo '==> registering Step Functions (skipped if ASL not delivered)'")
    for sf in spec.get("step_functions") or []:
        asl = sf["asl_path"]
        out.append(f'if [ -f "{attach}/asl/delivered/{Path(asl).name}" ] || [ -f "{attach}/asl/generated/{Path(asl).name}" ]; then')
        out.append(f'  echo "  registering {sf["state_machine_name"]} (ASL present)"')
        out.append(f'  # TODO: real ASL exists; wire up create-state-machine here')
        out.append(f'else')
        out.append(f'  echo "  SKIPPED {sf["state_machine_name"]} — ASL TAGGED-GAP"')
        out.append(f'fi')
    out.append("")

    # ─── Microcks imports ────────────────────────────────────────────────────
    # /api/artifact/upload is the right endpoint (Microcks 1.10+); /api/import
    # only queues an ImportJob and silently 200s on failure.
    out.append("echo '==> importing OpenAPIs into Microcks'")
    for c in spec.get("behavioral_contracts") or []:
        oapi = f'{c["name"]}.openapi.yaml'
        out.append(
            f'curl -fsS -X POST -F "file=@{attach}/contracts/generated/{oapi}" '
            f'"http://localhost:8080/api/artifact/upload" '
            f'-w "\\n  imported: %{{http_code}}\\n" || echo "  WARN: failed to import {oapi}"'
        )
    out.append("")

    # ─── FALLBACK dispatchers ────────────────────────────────────────────────
    # Microcks defaults to URI_PARAMS dispatcher which 404s any call that
    # doesn't exactly match an OpenAPI example's request signature. We patch
    # the operations to FALLBACK so unmatched calls still return a default
    # example. Without this, real test code that builds payloads dynamically
    # gets 404 from DBM/CAL and the smoke test fails for non-architectural
    # reasons.
    out.append(
        "echo '==> setting FALLBACK dispatchers so unmatched calls return a default example'"
    )
    out.append(
        'DBM_ID=$(curl -s "http://localhost:8080/api/services" | '
        'python3 -c "import json,sys;print([s[\'id\'] for s in json.load(sys.stdin) '
        'if \'DBM\' in s[\'name\']][0])" 2>/dev/null || echo "")'
    )
    out.append(
        'CAL_ID=$(curl -s "http://localhost:8080/api/services" | '
        'python3 -c "import json,sys;print([s[\'id\'] for s in json.load(sys.stdin) '
        'if \'CAL\' in s[\'name\']][0])" 2>/dev/null || echo "")'
    )
    out.append('if [ -n "$DBM_ID" ]; then')
    out.append(
        '  curl -fsS -X PUT '
        '"http://localhost:8080/api/services/$DBM_ID/operation?operationName=GET+%2Fquery" '
        '-H "Content-Type: application/json" '
        '-d \'{"dispatcher":"FALLBACK","dispatcherRules":"{\\"dispatcher\\":\\"URI_PARAMS\\",\\"dispatcherRules\\":\\"name\\",\\"fallback\\":\\"ccfa_tv_resolution\\"}","defaultDelay":0}\' '
        '>/dev/null && echo "  DBM /query → FALLBACK"'
    )
    out.append('fi')
    out.append('if [ -n "$CAL_ID" ]; then')
    out.append(
        '  curl -fsS -X PUT '
        '"http://localhost:8080/api/services/$CAL_ID/operation?operationName=GET+%2Fcalculation2%2Fstatus" '
        '-H "Content-Type: application/json" '
        '-d \'{"dispatcher":"FALLBACK","dispatcherRules":"{\\"dispatcher\\":\\"URI_PARAMS\\",\\"dispatcherRules\\":\\"execution_id\\",\\"fallback\\":\\"succeeded\\"}","defaultDelay":0}\' '
        '>/dev/null && echo "  CAL /calculation2/status → FALLBACK"'
    )
    out.append('fi')
    out.append("")

    out.append('echo "==> seeder complete"')
    out.append("")

    return "\n".join(out)
